### ISSUE TITLE
Notification e-mails hijacked

### ISSUE THREAD

**Issue by felixplesoianu** [jaywink/socialhome#303]
As of a week or two ago, whenever I receive a notification e-mail, the link in it (where it says "React to the reply here:") looks normal on the outside, but in fact points to a spammy URL. I thought it was a glitch the first time around, but it's clearly happening, and Thunderbird now rightfully thinks notification e-mails from Socialhome are suspicious.

**Comment by jaywink** [comment]
Do you mean the `mjt.lu` domain? This is owned by [Mailjet](https://www.mailjet.com/), a French mail delivery company. You can see the whois [here](https://who.is/whois/mjt.lu).

This issue isn't really related to Socialhome as in software, but more to socialhome.network, which is configured to use Mailjet for delivering emails. The reason is to ensure maximum reliability in delivering emails. Email is hard, unfortunately, and having notification emails go to spam would be bad.

However, I have realized since that not everybody likes emails delivered by these kind of delivery companies, especially once we go into notifications regarding private content. I have thus already begun initial work into setting up a proper self-hosted mail server that will deliver emails without using third-party providers - and hopefully not into the spam box.

Thanks for raising this.

**Comment by jaywink** [comment]
Sorry for not solving this earlier. I finally found out that it's possible to switch off the link click tracking in MailJet settings, which stops the links being polluted by `mjt.lu` domains and thus doesn't make at least Thunderbird for me think they're suspicious any more.

We're still moving to sending our own emails in the future, but for now I think this issue can be closed. If you still get warnings of new notifications emails after this change, please reopen.

Thanks for reporting!
