### ISSUE TITLE
Installed using docs, but cannot access site??

### ISSUE THREAD

**Issue by mitchellurgero** [jaywink/socialhome#387]
Site: https://urge.ro

I followed the documentation to a T (Changing passwords, etc of course) but I get a 503 error when access the site. Logs suggest uwsgi is not setup correctly maybe? or that socialhome services is not properly started. Any tips?

Yes the service starts and stays active as far as I can tell.

EDIT 

Part of log for you::

```
[Sat Dec 02 01:34:35.805127 2017] [proxy:error] [pid 2011:tid 140380066543360] AH00959: ap_proxy_connect_backend disabling worker for (127.0.0.1) for 60s
[Sat Dec 02 01:34:35.805145 2017] [:error] [pid 2011:tid 140380066543360]  failed to make connection to backend: 127.0.0.1:31452
[Sat Dec 02 01:37:51.668880 2017] [proxy:error] [pid 2012:tid 140379940652800] (111)Connection refused: AH00957: uwsgi: attempt to connect to 127.0.0.1:31452 (127.0.0.1) failed
```

EDIT 2

I have added ```retry=0``` to the ProxyPass lines in apache to disable it from disabling connections to the backend. Issue still persists. Nothing in socialhome.log either? How can I debug this?

**Comment by jaywink** [comment]
Hi @mitchellurgero . Sounds indeed like uwsgi is having problems.

Circus, which runs uWSGI, writes log into `/var/log/upstart/socialhome-circus.log`. You should see something pop in there if uWSGI crashes. Note that the service `socialhome` would still run, because it boots up many processes, not just uWSGI. If you're using something else than Ubuntu 14.04 the log might be in a different place.

If there is nothing here, could you check your `/home/socialhome/uwsgi.ini` matches the documentation or note if there are changes you have had to make?

**Comment by jaywink** [comment]
Btw there is a chat available via Gitter, IRC and Matrix if you want to jump in at some point for faster debugging :) https://socialhome.readthedocs.io/en/latest/community.html#feedback-and-community-chat

**Comment by mitchellurgero** [comment]
I am a goddamn idiot lol I had a typo in a file name. Thanks mate for the log location!

**Comment by jaywink** [comment]
Great it got solved! Did you have another issue with something, judging by the message on IRC? Sorry no one was available, I think we're on completely opposite time zones :/
