### ISSUE TITLE
Discussion: Please stop using TODO in checked-in code

### ISSUE THREAD

**Issue by Vir-Cotto** [jaywink/socialhome#396]
When working on a branch, I will often use TODOs to bookmark code and then use a tool like https://atom.io/packages/todo-show to show me all the TODOs in the project, removing them as I go. Then I know when the code is ready when there are no more TODOs left.

The problem in Socialhome is that there are TODOs littered throughout the code.

Can we turn those TODOs into issues, and then remove them from the code itself, followed by a pledge not to put TODOs in final code?

If we need a volunteer to do that, I'd be happy to volunteer to check all the TODOs against issues.

**Comment by jaywink** [comment]
I use TODO's for the same reason, except the life of a TODO is much longer. The IDE I use (PyCharm) also allows finding all TODO's, which I do sometimes to see if some of them can be removed. Having a TODO is also good when working on a piece of code when refactoring for example, to know what was missing from the current implementation that could be done while refactoring.

Unfortunately it's not possible to match the coding style of everyone within a single project. As the main developer spending the most time on the project, I'll have to rule in favour of the current practise, ie allowing TODO's in the code for example for the above usages. I'll add a note about this in the docs to "formalize" it, thanks for raising 👍 

Some TODO's for sure *might* belong to the issue tracker. I don't think all of them do though, many of them are small future tweaks or changes that can be added after some new feature (like the TODO's about supporting limited content in querysets). Even if they were mentioned in the issue I think they should still be mentioned in the code too, because of the refactoring related note above.

Would FIXME work instead for your use case for "need to fix before submitting a PR"? The package you linked supports that too in the same way as TODO.

Anyway, closing this. Doesn't mean discussion can't continue though :) Thanks for raising the idea!

**Comment by christophehenry** [comment]
Same opinion as @jaywink here. Socialhome is still in its early development. Not everything can be done yet and TODO's are handy to keep track of the work left on an epic. With the Vue migration, for instance, I use TODO to keep track of error managment that should be properly handled later. Does not belong to the tracker since they are saving points.
