### ISSUE TITLE
resharing from diasp.org produced duplicates

### ISSUE THREAD

**Issue by dvs1** [jaywink/socialhome#412]
After resharing some old posts from my diasp.org account,
my profile has duplicates of those reshares,
and also duplicates of content original to my socialhome account.

https://socialhome.network/u/dvs1/all/

**Comment by dvs1** [comment]
It seems to be the same block of posts repeated endlessly.

**Comment by christophehenry** [comment]
Indeed. Looks like a problem with our pagination system. Hopefully, this looks fixed in our new front-end (try it by adding `?vue=1` at the end of the URL), which will be released during FOSDEM in two weeks. I don't think it is worth fixing outdated code.

**Comment by dvs1** [comment]
Looking at the account via diasp.org, I don't see any duplicates.

On socialhome if I add `?vue=1` I don't see any duplicates,
but I also don't see all of my posts.

**Comment by christophehenry** [comment]
>  but I also don't see all of my posts.

But without, you do?

**Comment by dvs1** [comment]
No, just the same repeating group.

**Comment by jaywink** [comment]
Thanks for reporting, will check this today 👍

**Comment by christophehenry** [comment]
> No, just the same group repeated over and over again.

So there is two distinct problems. The repeating is already fixed in a soon to be released version. The other one may either be a federation problem or a pagination problem.

**Comment by jaywink** [comment]
So, been looking a bit into this finally and as @christophehenry said, we should not try to fix the old legacy stream since it will be gone in a week or so. But the bug in the Vue stream needs to be fixed, thanks again for reporting!

It seems, for some reason, the Vue stream is not rendering all the content it fetches. It goes around like this:

* First fetch gets 15 items (as it should)
* Vue renders the 15 items and places the load more on the 5th last item
* Scrolling down, second fetch gets 10 items (not sure why, in theory it should get 15 - this is a backend problem I've seen before, anyway, not causing this problem)
* Vue renders 4 items instead of 10. The load more is never places since it is in the 5th last item, which doesn't get rendered.
* Because these is no load more, no more items are fetched, even though the backend would most likely return more.

I have no idea from looking at the code why some of the items are not rendered, maybe @christophehenry you have some idea? I'll push in some console debugs, maybe that will help.

**Comment by jaywink** [comment]
OK after furious production debugging in development mode it seems this is a backend issue after all. The problem appears when the precalculated cache runs out of items and hits the first reshare. The queryset doesn't know what the `through` value should be and when I made it I just made it default to the same value as the content ID. This results in duplicate results being returned. Vue is smarter than the old stream not to rerender them, but it also means the load more never appears, thus, no more items. This problem is made worse by the fact that the older posts predate the precalculated streams, but still it needs to be made work since sometimes the cache might be emptied for various reasons.

All this technical mumbo jumbo aside, will need to either:
* generate a suitable through ID that will make load more work, or if not possible
* hack load more to always fetch more as long as even one more result is returned.

There is the time travel problem though, will need to think about this a bit. 

Related to #206

**Comment by jaywink** [comment]
Oh hmm. I fixed one thing but that didn't have the desired effect towards fixing this case it seems. Reopening, will continue investigating..

**Comment by jaywink** [comment]
Looks like fixed now! Was a combination of several tricky to hunt down bugs and inconsistent code. If you still think something is not right, please feel free to reopen 👍

**Comment by dvs1** [comment]
:sunglasses: :+1:
